services:
  - type: web
    name: umai-shop
    env: docker
    plan: free
    region: oregon
    dockerfilePath: ./Dockerfile
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        generateValue: true
      - key: APP_DEBUG
        value: false
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        fromDatabase:
          name: umai-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: umai-db
          property: port
      - key: DB_DATABASE
        fromDatabase:
          name: umai-db
          property: database
      - key: DB_USERNAME
        fromDatabase:
          name: umai-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: umai-db
          property: password
