services:
  - type: web
    name: bagisto-app
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    buildCommand: ""      # оставляем пустым
    startCommand: ""      # важно! пустым, так как Apache запускается внутри Dockerfile
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        generateValue: true
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        value: your-db-host
      - key: DB_PORT
        value: 3306
      - key: DB_DATABASE
        value: your-db-name
      - key: DB_USERNAME
        value: your-db-user
      - key: DB_PASSWORD
        value: your-db-password
